### ISSUE TITLE
Confusing use of Task Name: BPMN vs endpoints

### ISSUE THREAD

**Issue by StephenOTT** [kiegroup/kogito-runtimes#1900]
### Description

Consider the following config:

<img width="1394" alt="image" src="https://user-images.githubusercontent.com/1994838/150018673-ce4e9ec7-39d4-4c6c-a133-7324750e826e.png">

So the task name Must have no spaces.

If you arrive on this task the /tasks endpoint returns something like:

```json
[
  {
    "id": "3c5ed889-65c1-4120-8de4-bb0fd29e4130",
    "name": "Row2Task",
    "state": 0,
    "phase": "active",
    "phaseStatus": "Ready",
    "parameters": {},
    "results": {}
  }
]
```

The confusion is the `name` property. The name prop showing the value in the "Task Name" property in the BPMN.  But this is not a unique value, and is a ~system value rather than a human value to display in a task list.

**Comment by fjtirado** [comment]
The idea was that the "name" field in the task list returned by GET api can be used as path param for task endpoints as described here https://blog.kie.org/2021/05/kogito-user-tasks-process-api.html. Indeed, that name is unique and has nothing to be with the "name" property in the editor (which is just intended for visualization purposes) 
When choosing the name of the field "Task Name" seemed redundant, hence the most short "name". 
Due to the fact that is needed for pseudo HATEOAS (that name is part of the task URI) and that changing it will break backward compatibility, that name field must stay. 
So,the question is;
should we display in that list the name used in the visual editor to make easier the identification of the task? I though no, but since you, a smart user, got confused, I'm now tempted to say that we can add an additional field called "visual name" that shows it.

**Comment by StephenOTT** [comment]
well first it would see that "Task Name" in the modeler should be renamed to something like URI ID or equivalent.  But see https://github.com/kiegroup/kogito-tooling/issues/775 for further issues in this same space.

**Comment by fjtirado** [comment]
yes, I agree, that can be renames to "Task Id" and uniqueness enforced in the editor

**Comment by fjtirado** [comment]
Also, I have created JIRA for making the server fail if a process contains the same task name https://issues.redhat.com/browse/KOGITO-6592
