### ISSUE TITLE
Quarkus 3 support 

### ISSUE THREAD

**Issue by Emiliopg91** [kiegroup/kogito-runtimes#3196]
### Description

Good morning community

For my project I've been using Quarkus 2.X versions during early phases but now my company needs to upgrade to Quarkus 3.2.3.Final.
The problem is that during early phases, we integrated Kogito/Drools plugin and it worked in Quarkus 2.X but now, we migrated to Quarkus 3.2.3.Final and it seems not to have support for Kogito (no plugin version available, examples removed from quickstart...)

Has this plugin/module been deprecated? Will it be restored?

Can someone help me? We need to run DRL files and now that capacity is not available... any alternative? Will it be available soon?

**Comment by radtriste** [comment]
Hi @Emiliopg91 

The Jakarta update (Quarkus 3 / Spring Boot 3) is quite some work and is tracked on Zulip: https://kie.zulipchat.com/#narrow/stream/382044-kogito-dev/topic/Jakarta.20migration.20scripts

Due to limited resources, it is taking time. But I should be releasing a very first Alpha version in the next days.
Note that the Final won't arrive before October/November.
