### ISSUE TITLE
JSON Schema Validations with DMN Input model

### ISSUE THREAD

**Issue by ravim786** [kiegroup/kogito-runtimes#456]
I am forced to use existing pojo model for my DMN execution.  The pojo objects are created off of a json schema with a bunch of validations defined. 

1. Is it possible to validate the payload before DMN execution in Kogito?
2. Is it possible to force to use existing pojo model and not to generate again from DMN input model?
3. I tried to follow this thread - [DMN integration with OpenAPI support potential?](https://github.com/kiegroup/kogito-runtimes/issues/95) : if I keep my pojo model and dmn input model in sync (manually), it would help make a stronger OpenAPI definition? I did not understand and guess might not be related to what I need.

**Comment by tarilabs** [comment]
A1, A2:
the answer to that is **_scaffolding_**, as discussed in this email thread: https://groups.google.com/g/kogito-development/c/93-qVXXisKA/m/gbz52dToBQAJ

A3:
the related issue is considered resolved, ref https://github.com/kiegroup/kogito-runtimes/issues/95#issuecomment-679862224 since enabling "strongly typed" feature on Kogito (https://issues.redhat.com/browse/BAPL-1616) will also generate Swagger/OpenAPI definitions.

Considering this github issue resolved accordingly.
